[build]
  publish = "public" # This tells Netlify where your static HTML file is
  functions = "netlify/functions" # This tells Netlify where your functions are

# Optional: If you need to specify a Node.js version
[build.environment]
  NODE_VERSION = "18" # Or your preferred Node.js version
